#!/bin/bash

docker run --rm -p 3306:3306 -P \
   -e MYSQL_DATABASE=docker    \
   -e MYSQL_USER=docker        \
   -e MYSQL_PASSWORD=docker    \
   --name mysql_test orchardup/mysql > /dev/null 2>&1 &

export DBIITEST_MYSQL_DSN='dbi:mysql:database=docker;host=127.0.0.1;port=3306'
export DBIITEST_MYSQL_PASSWORD=docker
export DBIITEST_MYSQL_USER=docker

docker run --rm -p 5432:5432 -P --name pg_test postgres:9.3 > /dev/null 2>&1 &

export DBIITEST_PG_DSN='dbi:Pg:database=postgres;host=127.0.0.1;port=5432;user=postgres;password=postgres;'
export DBIITEST_PG_PASSWORD=postgres
export DBIITEST_PG_USER=postgres

# this takes too long to start for this to be comfortable
# docker run --rm -p 49160:22 -p 49161:1521 -P --name ora_test wnameless/oracle-xe-11g > /dev/null 2>&1 &

export DBIITEST_ORACLE_DSN='dbi:Oracle:xe'
export DBIITEST_ORACLE_PASSWORD=oracle
export DBIITEST_ORACLE_USER=system

# stupid databases
sleep 5

"$@"

docker stop mysql_test
docker stop pg_test
